### ISSUE TITLE
Tutorial fails

### ISSUE THREAD

**Issue by steven60411** [torchmd/torchmd-cg#19]
Hi! When I follow the tutorial steps to "from torchmd_cg.utils.prior_fit import get_param_bonded",
it will show up the module not found error
And when I check the path, only
['make_deltaforces.py', '__init__.py', 'mappings.py', '__pycache__', 'psfwriter.py']
are included
don't know if this is relate to my python version which couldn't pip install the full content of torchmd-cg?

**Comment by stefdoerr** [comment]
Hi Steven,
I assume you pulled this repo locally? If that's the case then `cd` into the top (torchmd-cg) directory and try `pip install .`
I think we need to make a new release for PyPI in the meanwhile.

**Comment by steven60411** [comment]
Okay! I'll try it. thanks a lot!

**Comment by stefdoerr** [comment]
I released a 0.0.2 version now. Maybe try first `pip install --upgrade torchmd-cg` to see if the PyPI version works.

**Comment by steven60411** [comment]
![image](https://user-images.githubusercontent.com/77240157/145157766-cca195e8-952c-414d-a698-e780c9a8bee9.png)

I think it worked!
