### ISSUE TITLE
Tutorial Training step fails

### ISSUE THREAD

**Issue by steven60411** [torchmd/torchmd-cg#20]
Hi!
When I try to follow the step for training in tutorial
An error said "ValueError: Unknown argument in config file: coords" popped
![image](https://user-images.githubusercontent.com/77240157/145168256-eafe4449-8d1e-4064-a411-f1b7d033fee3.png)

I've found that torchmdnet has been updated and the "light_train.py" in the scripts repo has been changed to "train.py"
So I change the command in tutorial to python $PATH/torchmd-net/scripts/**train.py** -c train.yaml
Don't know if it is the new .py file cause this error?

**Comment by stefdoerr** [comment]
Looking at https://github.com/torchmd/torchmd-net/blob/main/scripts/train.py it seems like the arguments to train.py have changed. I see coord_files instead of coords, same for forces and embeddings. I'm not totally sure on the right way to update this. @MaciejMajew can you take a look at fixing the tutorial?

**Comment by MaciejMajew** [comment]
We updated torchMD some weeks ago to allow using different types of network architectures, radial base functions, activation functions etc. Unfortunately we did not update the CG tutorial. I will try to fix that asap. Some arguments have changed, now the input should look like this
```activation: tanh
batch_size: 1024
dataset: Custom
coord_files: "data/chignolin_ca_coords.npy"
embed_files: "data/chignolin_ca_embeddings.npy"
force_files: "data/chignolin_ca_deltaforces.npy"
cutoff_upper: 9.0
derivative: true
distributed_backend: ddp
early_stopping_patience: 30
embedding_dimension: 128
log_dir: train_light
lr: 0.0001
lr_factor: 0.8
lr_min: 1.0e-06
lr_patience: 4
lr_warmup_steps: 0
max_num_neighbors: 128
model: graph-network
ngpus: 4
num_epochs: 200
num_layers: 3
num_nodes: 1
num_rbf: 150
num_workers: 8
rbf_type: gauss
save_interval: 1
seed: 1
test_interval: 1
test_size: 0.1
val_size: 0.05
```

**Comment by steven60411** [comment]
Hi! This is Steven
When I try to run the code above it shows error:

![image](https://user-images.githubusercontent.com/77240157/146493757-94d481e9-2bb3-468d-9a92-1b8f87f0acac.png)

Our team assume that this issue is from pytorch not working well with gpus, could be some torchmd issue? Don't know if it is right.
Can anyone help? These are the packages I installed in my environment:

```jsx：
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.7.4.post0              pypi_0    pypi
argon2-cffi               20.1.0           py39h27cfd23_1
ase                       3.22.0                   pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10               pyhd3eb1b0_0
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    4.0.0              pyhd3eb1b0_0
bottleneck                1.3.2            py39hdd57654_1
brotli                    1.0.9                he6710b0_2
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.14.6           py39h400218f_0
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.7                    pypi_0    pypi
cpuonly                   2.0                           0    pytorch
cryptography              3.4.8            py39hbca0aa6_0    conda-forge
cudatoolkit               10.1.243             h6bb024c_0
cycler                    0.10.0                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0
debugpy                   1.4.1            py39h295c915_0
decorator                 5.1.0              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3              py39h06a4308_0
expat                     2.4.1                h2531618_2
ffmpeg                    4.3                  hf484d3e_0    pytorch
fontconfig                2.13.1               h6c09931_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               h5ab3b9f_0
fsspec                    2021.10.1                pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
giflib                    5.2.1                h7b6447c_0
glib                      2.69.1               h5202010_0
gmp                       6.2.1                h2531618_2
gnutls                    3.6.15               he1e5248_0
google-auth               2.3.2                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
grpcio                    1.41.1                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
h5py                      3.5.0                    pypi_0    pypi
icu                       58.2                 he6710b0_3
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.8.1            py39h06a4308_0
importlib_metadata        4.8.1                hd3eb1b0_0
intel-openmp              2021.3.0          h06a4308_3350
ipykernel                 6.4.1            py39h06a4308_1
ipython                   7.27.0           py39hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
jedi                      0.18.0           py39h06a4308_1
jinja2                    3.0.1              pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9d                   h7f8727e_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter                   1.0.0            py39h06a4308_7
jupyter_client            7.0.1              pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.8.1            py39h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran-ng            7.5.0               ha8ba4b0_17
libgfortran4              7.5.0               ha8ba4b0_17
libgomp                   9.3.0               h5101ec6_17
libiconv                  1.15                 h63c8f33_5
libidn2                   2.3.2                h7f8727e_0
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              9.3.0               hd4cf53a_17
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.2.0                h85742a9_0
libunistring              0.9.10               h27cfd23_0
libuuid                   1.0.3                h7f8727e_2
libuv                     1.40.0               h7b6447c_0
libwebp                   1.2.0                h89dd481_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.12               h03d6c58_0
lz4-c                     1.9.3                h295c915_1
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py39h27cfd23_0
matplotlib                3.4.3            py39h06a4308_0
matplotlib-base           3.4.3            py39hbbc1b5f_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py39h27cfd23_1000
mkl                       2021.3.0           h06a4308_520
mkl-service               2.4.0            py39h7f8727e_0
mkl_fft                   1.3.1            py39hd3c417c_0
mkl_random                1.2.2            py39h51133e4_0
moleculekit               0.9.2                    pypi_0    pypi
multidict                 5.2.0                    pypi_0    pypi
munkres                   1.1.4                      py_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py39h06a4308_0
nbformat                  5.1.3              pyhd3eb1b0_0
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
nettle                    3.7.3                hbbd107a_1
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
notebook                  6.4.3            py39h06a4308_0
numexpr                   2.7.3            py39h22e1b3c_1
numpy                     1.21.2           py39h20f2e39_0
numpy-base                1.21.2           py39h79a1101_0
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0
openh264                  2.1.0                hd408876_0
openssl                   1.1.1l               h7f8727e_0
packaging                 21.0               pyhd3eb1b0_0
pandas                    1.3.4                    pypi_0    pypi
pandocfilters             1.4.3            py39h06a4308_1
parso                     0.8.2              pyhd3eb1b0_0
pcre                      8.45                 h295c915_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py39h5aabda8_0
pip                       21.2.4           py39h06a4308_0
prometheus_client         0.11.0             pyhd3eb1b0_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
prompt_toolkit            3.0.20               hd3eb1b0_0
protobuf                  3.19.0                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2
pydeprecate               0.3.0                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.3                    pypi_0    pypi
pyqt                      5.9.2            py39h2531618_6
pyrsistent                0.18.0           py39h7f8727e_0
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.7                h12debd9_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.10.0              py3.9_cpu_0    pytorch
pytorch-cluster           1.5.9           py39_torch_1.10.0_cpu    rusty1s
pytorch-geometric         2.0.2           py39_torch_1.10.0_cpu    rusty1s
pytorch-lightning         1.3.8                    pypi_0    pypi
pytorch-mutex             1.0                         cpu    pytorch
pytorch-scatter           2.0.9           py39_torch_1.10.0_cpu    rusty1s
pytorch-sparse            0.6.12          py39_torch_1.10.0_cpu    rusty1s
pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cpu    rusty1s
pytz                      2021.3                   pypi_0    pypi
pyyaml                    5.4.1            py39h27cfd23_1
pyzmq                     22.2.1           py39h295c915_1
qt                        5.9.7                h5867ecd_1
qtconsole                 5.1.1              pyhd3eb1b0_0
qtpy                      1.10.0             pyhd3eb1b0_0
readline                  8.1                  h27cfd23_0
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
schnetpack                1.0.0                    pypi_0    pypi
scikit-learn              1.0.1            py39h51133e4_0
scipy                     1.7.1            py39h292c36d_2
seaborn                   0.11.2             pyhd3eb1b0_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py39h06a4308_0
sip                       4.19.13          py39h2531618_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.4                      pypi_0    pypi
terminado                 0.9.4            py39h06a4308_0
testpath                  0.5.0              pyhd3eb1b0_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h1ccaba5_0
torchmd                   0.0.2                    pypi_0    pypi
torchmd-cg                0.0.2                    pypi_0    pypi
torchmd-net               0.2.0                     dev_0    <develop>
torchmetrics              0.5.1                    pypi_0    pypi
torchvision               0.11.1                 py39_cpu  [cpuonly]  pytorch
tornado                   6.1              py39h27cfd23_0
tqdm                      4.62.3             pyhd3eb1b0_1
traitlets                 5.1.0              pyhd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
tzdata                    2021e                hda174b7_0
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39h06a4308_1
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1
widgetsnbextension        3.5.1            py39h06a4308_0
xz                        5.2.5                h7b6447c_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h7b6447c_0
yarl                      1.7.0                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0

**Comment by MaciejMajew** [comment]
What is you CUDA driver version?

Have you tried running it with:
```CUDA_VISIBLE_DEVICES=0 python $PATH/scripts/train.py --conf train.yaml```

**Comment by steven60411** [comment]
Hi! Some update here

I change the ngpus in the train.yaml from 4 to 0, and it looks like the training is running fine now. But still need to check the result after it completes

Here is what it looks like now:
![image](https://user-images.githubusercontent.com/77240157/146541450-672af302-b81f-47c2-89c3-cc30e0219241.png)

**Comment by MaciejMajew** [comment]
You can change `ngpus` to -1 and determine which devices to run on by `CUDA_VISIBLE_DEVICES`

**Comment by steven60411** [comment]
Got it! Thanks a lot

**Comment by poroussong** [comment]
> Hi! This is Steven When I try to run the code above it shows error:
> 
> ![image](https://user-images.githubusercontent.com/77240157/146493757-94d481e9-2bb3-468d-9a92-1b8f87f0acac.png)
> 
> Our team assume that this issue is from pytorch not working well with gpus, could be some torchmd issue? Don't know if it is right. Can anyone help? These are the packages I installed in my environment:
> 
> ```
> Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main
> _openmp_mutex             4.5                       1_gnu
> absl-py                   0.15.0                   pypi_0    pypi
> aiohttp                   3.7.4.post0              pypi_0    pypi
> argon2-cffi               20.1.0           py39h27cfd23_1
> ase                       3.22.0                   pypi_0    pypi
> async-timeout             3.0.1                    pypi_0    pypi
> async_generator           1.10               pyhd3eb1b0_0
> attrs                     21.2.0             pyhd3eb1b0_0
> backcall                  0.2.0              pyhd3eb1b0_0
> blas                      1.0                         mkl
> bleach                    4.0.0              pyhd3eb1b0_0
> bottleneck                1.3.2            py39hdd57654_1
> brotli                    1.0.9                he6710b0_2
> brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
> bzip2                     1.0.8                h7b6447c_0
> ca-certificates           2021.10.8            ha878542_0    conda-forge
> cachetools                4.2.4                    pypi_0    pypi
> certifi                   2021.10.8        py39hf3d152e_1    conda-forge
> cffi                      1.14.6           py39h400218f_0
> chardet                   4.0.0                    pypi_0    pypi
> charset-normalizer        2.0.7                    pypi_0    pypi
> cpuonly                   2.0                           0    pytorch
> cryptography              3.4.8            py39hbca0aa6_0    conda-forge
> cudatoolkit               10.1.243             h6bb024c_0
> cycler                    0.10.0                   pypi_0    pypi
> dbus                      1.13.18              hb2f20db_0
> debugpy                   1.4.1            py39h295c915_0
> decorator                 5.1.0              pyhd3eb1b0_0
> defusedxml                0.7.1              pyhd3eb1b0_0
> entrypoints               0.3              py39h06a4308_0
> expat                     2.4.1                h2531618_2
> ffmpeg                    4.3                  hf484d3e_0    pytorch
> fontconfig                2.13.1               h6c09931_0
> fonttools                 4.25.0             pyhd3eb1b0_0
> freetype                  2.10.4               h5ab3b9f_0
> fsspec                    2021.10.1                pypi_0    pypi
> future                    0.18.2                   pypi_0    pypi
> giflib                    5.2.1                h7b6447c_0
> glib                      2.69.1               h5202010_0
> gmp                       6.2.1                h2531618_2
> gnutls                    3.6.15               he1e5248_0
> google-auth               2.3.2                    pypi_0    pypi
> google-auth-oauthlib      0.4.6                    pypi_0    pypi
> googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
> grpcio                    1.41.1                   pypi_0    pypi
> gst-plugins-base          1.14.0               h8213a91_2
> gstreamer                 1.14.0               h28cd5cc_2
> h5py                      3.5.0                    pypi_0    pypi
> icu                       58.2                 he6710b0_3
> idna                      3.3                      pypi_0    pypi
> importlib-metadata        4.8.1            py39h06a4308_0
> importlib_metadata        4.8.1                hd3eb1b0_0
> intel-openmp              2021.3.0          h06a4308_3350
> ipykernel                 6.4.1            py39h06a4308_1
> ipython                   7.27.0           py39hb070fc8_0
> ipython_genutils          0.2.0              pyhd3eb1b0_1
> ipywidgets                7.6.5              pyhd3eb1b0_1
> jedi                      0.18.0           py39h06a4308_1
> jinja2                    3.0.1              pyhd3eb1b0_0
> joblib                    1.0.1              pyhd3eb1b0_0
> jpeg                      9d                   h7f8727e_0
> jsonschema                3.2.0              pyhd3eb1b0_2
> jupyter                   1.0.0            py39h06a4308_7
> jupyter_client            7.0.1              pyhd3eb1b0_0
> jupyter_console           6.4.0              pyhd3eb1b0_0
> jupyter_core              4.8.1            py39h06a4308_0
> jupyterlab_pygments       0.1.2                      py_0
> jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
> kiwisolver                1.3.2                    pypi_0    pypi
> lame                      3.100                h7b6447c_0
> lcms2                     2.12                 h3be6417_0
> ld_impl_linux-64          2.35.1               h7274673_9
> libffi                    3.3                  he6710b0_2
> libgcc-ng                 9.3.0               h5101ec6_17
> libgfortran-ng            7.5.0               ha8ba4b0_17
> libgfortran4              7.5.0               ha8ba4b0_17
> libgomp                   9.3.0               h5101ec6_17
> libiconv                  1.15                 h63c8f33_5
> libidn2                   2.3.2                h7f8727e_0
> libpng                    1.6.37               hbc83047_0
> libsodium                 1.0.18               h7b6447c_0
> libstdcxx-ng              9.3.0               hd4cf53a_17
> libtasn1                  4.16.0               h27cfd23_0
> libtiff                   4.2.0                h85742a9_0
> libunistring              0.9.10               h27cfd23_0
> libuuid                   1.0.3                h7f8727e_2
> libuv                     1.40.0               h7b6447c_0
> libwebp                   1.2.0                h89dd481_0
> libwebp-base              1.2.0                h27cfd23_0
> libxcb                    1.14                 h7b6447c_0
> libxml2                   2.9.12               h03d6c58_0
> lz4-c                     1.9.3                h295c915_1
> markdown                  3.3.4                    pypi_0    pypi
> markupsafe                2.0.1            py39h27cfd23_0
> matplotlib                3.4.3            py39h06a4308_0
> matplotlib-base           3.4.3            py39hbbc1b5f_0
> matplotlib-inline         0.1.2              pyhd3eb1b0_2
> mistune                   0.8.4           py39h27cfd23_1000
> mkl                       2021.3.0           h06a4308_520
> mkl-service               2.4.0            py39h7f8727e_0
> mkl_fft                   1.3.1            py39hd3c417c_0
> mkl_random                1.2.2            py39h51133e4_0
> moleculekit               0.9.2                    pypi_0    pypi
> multidict                 5.2.0                    pypi_0    pypi
> munkres                   1.1.4                      py_0
> nbclient                  0.5.3              pyhd3eb1b0_0
> nbconvert                 6.1.0            py39h06a4308_0
> nbformat                  5.1.3              pyhd3eb1b0_0
> ncurses                   6.2                  he6710b0_1
> nest-asyncio              1.5.1              pyhd3eb1b0_0
> nettle                    3.7.3                hbbd107a_1
> networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
> notebook                  6.4.3            py39h06a4308_0
> numexpr                   2.7.3            py39h22e1b3c_1
> numpy                     1.21.2           py39h20f2e39_0
> numpy-base                1.21.2           py39h79a1101_0
> oauthlib                  3.1.1                    pypi_0    pypi
> olefile                   0.46               pyhd3eb1b0_0
> openh264                  2.1.0                hd408876_0
> openssl                   1.1.1l               h7f8727e_0
> packaging                 21.0               pyhd3eb1b0_0
> pandas                    1.3.4                    pypi_0    pypi
> pandocfilters             1.4.3            py39h06a4308_1
> parso                     0.8.2              pyhd3eb1b0_0
> pcre                      8.45                 h295c915_0
> pexpect                   4.8.0              pyhd3eb1b0_3
> pickleshare               0.7.5           pyhd3eb1b0_1003
> pillow                    8.4.0            py39h5aabda8_0
> pip                       21.2.4           py39h06a4308_0
> prometheus_client         0.11.0             pyhd3eb1b0_0
> prompt-toolkit            3.0.20             pyhd3eb1b0_0
> prompt_toolkit            3.0.20               hd3eb1b0_0
> protobuf                  3.19.0                   pypi_0    pypi
> ptyprocess                0.7.0              pyhd3eb1b0_2
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pycparser                 2.20                       py_2
> pydeprecate               0.3.0                    pypi_0    pypi
> pygments                  2.10.0             pyhd3eb1b0_0
> pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
> pyparsing                 3.0.3                    pypi_0    pypi
> pyqt                      5.9.2            py39h2531618_6
> pyrsistent                0.18.0           py39h7f8727e_0
> pysocks                   1.7.1            py39hf3d152e_4    conda-forge
> python                    3.9.7                h12debd9_1
> python-dateutil           2.8.2              pyhd3eb1b0_0
> python-louvain            0.15               pyhd3deb0d_0    conda-forge
> python_abi                3.9                      2_cp39    conda-forge
> pytorch                   1.10.0              py3.9_cpu_0    pytorch
> pytorch-cluster           1.5.9           py39_torch_1.10.0_cpu    rusty1s
> pytorch-geometric         2.0.2           py39_torch_1.10.0_cpu    rusty1s
> pytorch-lightning         1.3.8                    pypi_0    pypi
> pytorch-mutex             1.0                         cpu    pytorch
> pytorch-scatter           2.0.9           py39_torch_1.10.0_cpu    rusty1s
> pytorch-sparse            0.6.12          py39_torch_1.10.0_cpu    rusty1s
> pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cpu    rusty1s
> pytz                      2021.3                   pypi_0    pypi
> pyyaml                    5.4.1            py39h27cfd23_1
> pyzmq                     22.2.1           py39h295c915_1
> qt                        5.9.7                h5867ecd_1
> qtconsole                 5.1.1              pyhd3eb1b0_0
> qtpy                      1.10.0             pyhd3eb1b0_0
> readline                  8.1                  h27cfd23_0
> requests                  2.26.0             pyhd8ed1ab_1    conda-forge
> requests-oauthlib         1.3.0                    pypi_0    pypi
> rsa                       4.7.2                    pypi_0    pypi
> schnetpack                1.0.0                    pypi_0    pypi
> scikit-learn              1.0.1            py39h51133e4_0
> scipy                     1.7.1            py39h292c36d_2
> seaborn                   0.11.2             pyhd3eb1b0_0
> send2trash                1.8.0              pyhd3eb1b0_1
> setuptools                58.0.4           py39h06a4308_0
> sip                       4.19.13          py39h2531618_0
> six                       1.16.0             pyhd3eb1b0_0
> sqlite                    3.36.0               hc218d9a_0
> tensorboard               2.7.0                    pypi_0    pypi
> tensorboard-data-server   0.6.1                    pypi_0    pypi
> tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
> tensorboardx              2.4                      pypi_0    pypi
> terminado                 0.9.4            py39h06a4308_0
> testpath                  0.5.0              pyhd3eb1b0_0
> threadpoolctl             2.2.0              pyh0d69192_0
> tk                        8.6.11               h1ccaba5_0
> torchmd                   0.0.2                    pypi_0    pypi
> torchmd-cg                0.0.2                    pypi_0    pypi
> torchmd-net               0.2.0                     dev_0    <develop>
> torchmetrics              0.5.1                    pypi_0    pypi
> torchvision               0.11.1                 py39_cpu  [cpuonly]  pytorch
> tornado                   6.1              py39h27cfd23_0
> tqdm                      4.62.3             pyhd3eb1b0_1
> traitlets                 5.1.0              pyhd3eb1b0_0
> typing_extensions         3.10.0.2           pyh06a4308_0
> tzdata                    2021e                hda174b7_0
> urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
> wcwidth                   0.2.5              pyhd3eb1b0_0
> webencodings              0.5.1            py39h06a4308_1
> werkzeug                  2.0.2                    pypi_0    pypi
> wheel                     0.37.0             pyhd3eb1b0_1
> widgetsnbextension        3.5.1            py39h06a4308_0
> xz                        5.2.5                h7b6447c_0
> yacs                      0.1.6                      py_0    conda-forge
> yaml                      0.2.5                h7b6447c_0
> yarl                      1.7.0                    pypi_0    pypi
> zeromq                    4.3.4                h2531618_0
> zipp                      3.6.0              pyhd3eb1b0_0
> zlib                      1.2.11               h7b6447c_3
> zstd                      1.4.9                haebb681_0
> ```

Hi Steven,

I was wondering under which environment you output the info of all packages. I tried conda list under different envs like torchmd, torchmd-net, torchmd_cg, it gives me different info. Some contain torchmd while some don't.

Regards,

Zhe
