### ISSUE TITLE
Data set preparation problems for coarse-grained ionic liquids

### ISSUE THREAD

**Issue by mukui123** [torchmd/torchmd-cg#28]
Hello dear, after running through the example of protein coarse-grained simulation, I want to try the coarse-grained ionic liquid, but I have encountered problems in the process of data set preparation. For the chemical structure, it seems that it cannot be converted into psf file format. If I want to try the coarse particle size of ionic liquid, what should I pay attention to?

**Comment by MaciejMajew** [comment]
Hello. PSFwriter was designed to convert proteins into CA or CACB coarse-grained representation. First it extracts relevant atoms by their atoms names so it will most likely not work for ionic liquid (onles you have multiple atoms with the name 'CA' or 'CB'). The code is however fairly simple and you can adjust it to coarse-grain your molecules. Moleculekit is quite handy with that (free for academic use, but requires license for commercial use, you need to run torchmd anyway) but it can be done also with a bunch of other packages. 

If you are going to use the NNP only then psf only has to have atoms in it (no need to pay attention to bonding, angles etc). However if you are also using prior force terms with your system you should pay attention the the force terms you are going to use are also reflected in the PSF file you create.
