### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by Mo379** [torchmd/torchmd-cg#29]
Hi,

I've been spending sometime trying to reporduce the torch-MD paper on Jax, I followed the example notebook given with that. My issue is that I would like to reproduce the training too, but i cannot seem to find the full dataset of the chignolin trajectory with forces.

Would anyone be able to help with this if possible ? 

Thanks

**Comment by MaciejMajew** [comment]
Hi, Thanks for the interest. 

We share the dataset for chignolin (and other small fast-folding proteins) in another repo associated with our recent preprint: https://arxiv.org/abs/2212.07492

Here you can download the data:
https://github.com/torchmd/torchmd-protein-thermodynamics/tree/main/Datasets

Let me know if that is what you are looking for.
